009

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,6 +20,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Download Resources (Pre-Build)
+        run: |
+          echo "Downloading OpenGApps..."
+          wget --user-agent="Mozilla/5.0" -O opengapps.zip "https://master.dl.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip?viasf=1"
+          echo "Verifying file size..."
+          ls -lh opengapps.zip
+          if [ -s opengapps.zip ]; then echo "Download Success"; else echo "Download Failed"; exit 1; fi
+
       - name: Log in to the Container registry
         uses: docker/login-action@v2
         with:
